title: 光明小界
email:  
description: 
baseurl:  
username: guanjiayang
github_username:  guanjiayang
permalink: /:year/:month/:day/:title/
safe: false
markdown: kramdown
#highlighter: pygments
highlighter: rouge
paginate: 15
paginate_path: "page:num"
gems: [jekyll-paginate]
refurl: "http://csmi.top"  #the base url of the site

# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
# baseurl: ""  #the subpath of the site, e.g. /blog/
# url: "http://yourdomain.com"  #the base url of the site
# twitter_username:

theme: jekyll-theme-slate